/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Keyboard Events
 #	author : miyako
 #	2016/09/05
 #
 # --------------------------------------------------------------------------------*/



// --- Keyboard
void ON_RAW_KEYDOWN_CALL(sLONG_PTR *pResult, PackagePtr pParams);

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_Unichar* process_name_t;

void listenerLoop(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);